title: Team 5458

baseurl: ""
url: "0.0.0.0"
sass: 
    style: compressed

markdown: kramdown

exclude:
- README.md

include: 
- _pages

collections_dir: data
collections:
  history:
    output: false
  sponsors:
    output: false
  robots:
    output: true
    permalink: /robots/:name